/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import clases.Fraccion;
import clases.Mixto;
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEntero1 = new javax.swing.JTextField();
        txtNum1 = new javax.swing.JTextField();
        txtDen1 = new javax.swing.JTextField();
        txtNum2 = new javax.swing.JTextField();
        txtDen2 = new javax.swing.JTextField();
        txtEntero2 = new javax.swing.JTextField();
        cmdCalcular = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmbOperacion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtEntero3 = new javax.swing.JTextField();
        txtNum3 = new javax.swing.JTextField();
        txtDen3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        txtDen = new javax.swing.JTextField();
        cmdFraccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("OPERACIONES NÚMEROS MIXTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 300, -1));

        txtEntero1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEntero1KeyTyped(evt);
            }
        });
        jPanel1.add(txtEntero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 40, 30));

        txtNum1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum1KeyTyped(evt);
            }
        });
        jPanel1.add(txtNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 40, 30));

        txtDen1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDen1KeyTyped(evt);
            }
        });
        jPanel1.add(txtDen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 40, 30));

        txtNum2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum2KeyTyped(evt);
            }
        });
        jPanel1.add(txtNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 40, 30));

        txtDen2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDen2KeyTyped(evt);
            }
        });
        jPanel1.add(txtDen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 40, 30));

        txtEntero2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEntero2KeyTyped(evt);
            }
        });
        jPanel1.add(txtEntero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 40, 30));

        cmdCalcular.setText("Cacular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicacion", "Division" }));
        jPanel1.add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 80, -1));

        jLabel2.setText("=");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 60, 10, -1));

        txtEntero3.setEditable(false);
        jPanel1.add(txtEntero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 40, 30));

        txtNum3.setEditable(false);
        jPanel1.add(txtNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 40, 30));

        txtDen3.setEditable(false);
        jPanel1.add(txtDen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 40, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("A Fraccion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        txtNum.setEditable(false);
        jPanel1.add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 40, 30));

        txtDen.setEditable(false);
        jPanel1.add(txtDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 40, 30));

        cmdFraccion.setText("Convertir a Fraccion");
        cmdFraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFraccionActionPerformed(evt);
            }
        });
        jPanel1.add(cmdFraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
      int op ,e1 ,e2, n1 , n2, d1 , d2;
      Mixto m1 , m2 ,m3 = null;
     
       
     if(txtNum1.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite numerador numero 1","Error", JOptionPane.ERROR_MESSAGE);
         txtNum1.requestFocusInWindow();
     }else if(txtDen1.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite denominador numero 1","Error", JOptionPane.ERROR_MESSAGE);
         txtDen1.requestFocusInWindow();
     }else if(txtNum2.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite numerador numero 2","Error", JOptionPane.ERROR_MESSAGE);
         txtNum2.requestFocusInWindow();
     }else if(txtDen2.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite denominador numero 2","Error",JOptionPane.ERROR_MESSAGE);
         txtDen2.requestFocusInWindow();
         }else if(txtEntero1.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite Entero numero1","Error",JOptionPane.ERROR_MESSAGE);
         txtEntero1.requestFocusInWindow();
         }else if(txtEntero2.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite Entero numero 2","Error",JOptionPane.ERROR_MESSAGE);
         txtEntero2.requestFocusInWindow();
     }else{
         
     }
       op= cmbOperacion.getSelectedIndex();
       e1=Integer.parseInt(txtEntero1.getText());
       n1=Integer.parseInt(txtNum1.getText());
       d1=Integer.parseInt(txtDen1.getText());
       e2=Integer.parseInt(txtEntero2.getText());
       n2=Integer.parseInt(txtNum2.getText());
       d2=Integer.parseInt(txtDen2.getText());
       
       m1= new Mixto(e1,n1,d1);
       m2= new Mixto(e2,n2,d2);
       
       switch(op){
           case 0:
               m3 = m1.Sumar(m2);
               break;
           case 1:
               m3 = m1.Resta(m2);
               break;
           case 2:
               m3=m1.Multiplicacion(m2);
               break;
           case 3:
               m3=m1.Division(m2);
       }
       
       txtEntero3.setText(""+m3.getEntero());
       txtNum3.setText(""+m3.getNumerador());
       txtDen3.setText(""+m3.getDenominador());
     
    

   
        
      
  
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
      txtDen.setText("");
      txtDen1.setText("");
      txtDen2.setText("");
      txtDen3.setText("");
      txtEntero1.setText("");
      txtEntero2.setText("");
      txtEntero3.setText("");
      txtNum.setText("");
      txtNum1.setText("");
      txtNum2.setText("");
      txtNum3.setText("");
      
      
      txtEntero1.requestFocusInWindow();
       cmbOperacion.setSelectedIndex(0);
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdFraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFraccionActionPerformed
       Fraccion m1,m2,m3 = null;
       int num,den,ent,numerador,denominador;
       
      
       num = Integer.parseInt(txtNum3.getText());
       den = Integer.parseInt(txtDen3.getText());
       ent = Integer.parseInt(txtEntero3.getText());
       
       numerador=ent*den;
       denominador=den;
       
       
       m1 = new Fraccion (numerador,denominador);
       m3=m1.Fraccion();
       txtNum.setText(""+m3.getNumerador());
       txtDen.setText(""+m3.getDenominador());
       
    }//GEN-LAST:event_cmdFraccionActionPerformed

    private void txtEntero1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntero1KeyTyped
       char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              
              evt.consume(); 
                      
          } 
    }//GEN-LAST:event_txtEntero1KeyTyped

    private void txtNum1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum1KeyTyped
     char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              
              evt.consume(); 
                      
          } 
    }//GEN-LAST:event_txtNum1KeyTyped

    private void txtDen1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDen1KeyTyped
       char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              
              evt.consume(); 
                      
          } 
    }//GEN-LAST:event_txtDen1KeyTyped

    private void txtEntero2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntero2KeyTyped
      char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              
              evt.consume(); 
                      
          } 
    }//GEN-LAST:event_txtEntero2KeyTyped

    private void txtNum2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum2KeyTyped
      char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              
              evt.consume(); 
                      
          } 
    }//GEN-LAST:event_txtNum2KeyTyped

    private void txtDen2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDen2KeyTyped
       char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              
              evt.consume(); 
                      
          } 
    }//GEN-LAST:event_txtDen2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdFraccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDen;
    private javax.swing.JTextField txtDen1;
    private javax.swing.JTextField txtDen2;
    private javax.swing.JTextField txtDen3;
    private javax.swing.JTextField txtEntero1;
    private javax.swing.JTextField txtEntero2;
    private javax.swing.JTextField txtEntero3;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextField txtNum3;
    // End of variables declaration//GEN-END:variables
}
